# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib skiagd, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}

# Prohibit modifying environments

#' @export
`$<-.savvy_skiagd__sealed` <- function(x, name, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`[[<-.savvy_skiagd__sealed` <- function(x, i, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' Fills canvas with color
#'
#' @param size Canvas size.
#' @param fill Integers length 4 (RGBA).
#' @returns A raw vector of picture.
#' @noRd
`sk_absolute_fill` <- function(`size`, `fill`) {
  .Call(savvy_sk_absolute_fill__impl, `size`, `fill`)
}

#' Takes a raw vector of picture and returns PNG data
#'
#' @param size Canvas size.
#' @param curr_bytes Current canvas state.
#' @param mat Matrix for transforming picture.
#' @returns A raw vector of PNG data.
#' @noRd
`sk_as_png` <- function(`size`, `curr_bytes`, `mat`) {
  .Call(savvy_sk_as_png__impl, `size`, `curr_bytes`, `mat`)
}

#' Draws circle on canvas
#'
#' @param size Canvas size.
#' @param curr_bytes Current canvas state.
#' @param mat Matrix for transforming picture.
#' @param x X coordinates of center.
#' @param y Y coordinates of center.
#' @param radius Circle radius.
#' @returns A raw vector of picture.
#' @noRd
`sk_draw_circle` <- function(`size`, `curr_bytes`, `mat`, `props`, `x`, `y`, `radius`) {
  `props` <- .savvy_extract_ptr(`props`, "PaintProps")
  .Call(savvy_sk_draw_circle__impl, `size`, `curr_bytes`, `mat`, `props`, `x`, `y`, `radius`)
}

#' Draws rectangle on canvas
#'
#' @param size Canvas size.
#' @param curr_bytes Current canvas state.
#' @param mat Matrix for transforming picture.
#' @param props PaintProps.
#' @param left X coordinates of the left edge of the rectangles.
#' @param top Y coordinates of the top edge of the rectangles.
#' @param right X coordinates of the right edge of the rectangles.
#' @param bottom Y coordinates of the bottom edge of the rectangles.
#' @returns A raw vector of picture.
#' @noRd
`sk_draw_irect` <- function(`size`, `curr_bytes`, `mat`, `props`, `left`, `top`, `right`, `bottom`) {
  `props` <- .savvy_extract_ptr(`props`, "PaintProps")
  .Call(savvy_sk_draw_irect__impl, `size`, `curr_bytes`, `mat`, `props`, `left`, `top`, `right`, `bottom`)
}

#' Draws lines on canvas
#'
#' @param size Canvas size.
#' @param curr_bytes Current canvas state.
#' @param mat Matrix for transforming picture.
#' @param props PaintProps.
#' @param from_x X coordinates of start points.
#' @param from_y Y coordinates of start points.
#' @param to_x X coordinates of end points.
#' @param to_y Y coordinates of end points.
#' @returns A raw vector of picture.
#' @noRd
`sk_draw_line` <- function(`size`, `curr_bytes`, `mat`, `props`, `from_x`, `from_y`, `to_x`, `to_y`) {
  `props` <- .savvy_extract_ptr(`props`, "PaintProps")
  .Call(savvy_sk_draw_line__impl, `size`, `curr_bytes`, `mat`, `props`, `from_x`, `from_y`, `to_x`, `to_y`)
}

#' Draws SVG path on canvas
#'
#' @param size Canvas size.
#' @param curr_bytes Current canvas state.
#' @param mat Matrix for transforming picture.
#' @param props PaintProps.
#' @param svg SVG strings to draw.
#' @returns A raw vector of picture.
#' @noRd
`sk_draw_path` <- function(`size`, `curr_bytes`, `mat`, `props`, `svg`) {
  `props` <- .savvy_extract_ptr(`props`, "PaintProps")
  .Call(savvy_sk_draw_path__impl, `size`, `curr_bytes`, `mat`, `props`, `svg`)
}

#' Draws PNG data as an image on canvas
#'
#' @param size Canvas size.
#' @param curr_bytes Current canvas state.
#' @param mat Matrix for transforming picture.
#' @param props PaintProps.
#' @param png_bytes PNG data to draw.
#' @param left_top Offset for drawing PNG image.
#' @returns A raw vector of picture.
#' @noRd
`sk_draw_png` <- function(`size`, `curr_bytes`, `mat`, `props`, `png_bytes`, `left_top`) {
  `props` <- .savvy_extract_ptr(`props`, "PaintProps")
  .Call(savvy_sk_draw_png__impl, `size`, `curr_bytes`, `mat`, `props`, `png_bytes`, `left_top`)
}

#' Draws points with specified mode
#'
#' @param size Canvas size.
#' @param curr_bytes Current canvas state.
#' @param mat Matrix for transforming picture.
#' @param x X coordinates of points.
#' @param y Y coordinates of points.
#' @param mode PointMode.
#' @returns A raw vector of picture.
#' @noRd
`sk_draw_points` <- function(`size`, `curr_bytes`, `mat`, `props`, `x`, `y`, `mode`) {
  `props` <- .savvy_extract_ptr(`props`, "PaintProps")
  `mode` <- .savvy_extract_ptr(`mode`, "PointMode")
  .Call(savvy_sk_draw_points__impl, `size`, `curr_bytes`, `mat`, `props`, `x`, `y`, `mode`)
}

#' Returns default matrix as numerics
#'
#' @details
#' Users should not touch matrix to transform pictures.
#' For a `canvas.draw_picture()` call, pass `Paint::default()`.
#'
#' @returns A numeric vector length 9.
#' @noRd
`sk_matrix_default` <- function() {
  .Call(savvy_sk_matrix_default__impl)
}

### wrapper functions for BlendMode


`.savvy_wrap_BlendMode` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr


  class(e) <- c("BlendMode", "savvy_skiagd__sealed")
  e
}


#' BlendMode (0-28)
#'
#' @seealso
#' [BlendMode in skia_safe - Rust](https://rust-skia.github.io/doc/skia_safe/enum.BlendMode.html)
#' @export
`BlendMode` <- new.env(parent = emptyenv())
`BlendMode`$`Clear` <- .savvy_wrap_BlendMode(0L)
`BlendMode`$`Src` <- .savvy_wrap_BlendMode(1L)
`BlendMode`$`Dst` <- .savvy_wrap_BlendMode(2L)
`BlendMode`$`SrcOver` <- .savvy_wrap_BlendMode(3L)
`BlendMode`$`DstOver` <- .savvy_wrap_BlendMode(4L)
`BlendMode`$`SrcIn` <- .savvy_wrap_BlendMode(5L)
`BlendMode`$`DstIn` <- .savvy_wrap_BlendMode(6L)
`BlendMode`$`SrcOut` <- .savvy_wrap_BlendMode(7L)
`BlendMode`$`DstOut` <- .savvy_wrap_BlendMode(8L)
`BlendMode`$`SrcATop` <- .savvy_wrap_BlendMode(9L)
`BlendMode`$`DstATop` <- .savvy_wrap_BlendMode(10L)
`BlendMode`$`Xor` <- .savvy_wrap_BlendMode(11L)
`BlendMode`$`Plus` <- .savvy_wrap_BlendMode(12L)
`BlendMode`$`Modulate` <- .savvy_wrap_BlendMode(13L)
`BlendMode`$`Screen` <- .savvy_wrap_BlendMode(14L)
`BlendMode`$`Overlay` <- .savvy_wrap_BlendMode(15L)
`BlendMode`$`Darken` <- .savvy_wrap_BlendMode(16L)
`BlendMode`$`Lighten` <- .savvy_wrap_BlendMode(17L)
`BlendMode`$`ColorDodge` <- .savvy_wrap_BlendMode(18L)
`BlendMode`$`ColorBurn` <- .savvy_wrap_BlendMode(19L)
`BlendMode`$`HardLight` <- .savvy_wrap_BlendMode(20L)
`BlendMode`$`SoftLight` <- .savvy_wrap_BlendMode(21L)
`BlendMode`$`Difference` <- .savvy_wrap_BlendMode(22L)
`BlendMode`$`Exclusion` <- .savvy_wrap_BlendMode(23L)
`BlendMode`$`Multiply` <- .savvy_wrap_BlendMode(24L)
`BlendMode`$`Hue` <- .savvy_wrap_BlendMode(25L)
`BlendMode`$`Saturation` <- .savvy_wrap_BlendMode(26L)
`BlendMode`$`Color` <- .savvy_wrap_BlendMode(27L)
`BlendMode`$`Luminosity` <- .savvy_wrap_BlendMode(28L)

#' @export
`$.BlendMode__bundle` <- function(x, name) {
  if (!name %in% c("Clear", "Src", "Dst", "SrcOver", "DstOver", "SrcIn", "DstIn", "SrcOut", "DstOut", "SrcATop", "DstATop", "Xor", "Plus", "Modulate", "Screen", "Overlay", "Darken", "Lighten", "ColorDodge", "ColorBurn", "HardLight", "SoftLight", "Difference", "Exclusion", "Multiply", "Hue", "Saturation", "Color", "Luminosity")) {
    stop(paste0("Unknown variant: ", name), call. = FALSE)
  }

  NextMethod()
}

#' @export
`[[.BlendMode__bundle` <- function(x, i) {
  if (is.numeric(i)) {
    stop("BlendMode cannot be subset by index", call. = FALSE)
  }

  if (!i %in% c("Clear", "Src", "Dst", "SrcOver", "DstOver", "SrcIn", "DstIn", "SrcOut", "DstOut", "SrcATop", "DstATop", "Xor", "Plus", "Modulate", "Screen", "Overlay", "Darken", "Lighten", "ColorDodge", "ColorBurn", "HardLight", "SoftLight", "Difference", "Exclusion", "Multiply", "Hue", "Saturation", "Color", "Luminosity")) {
    stop(paste0("Unknown variant: ", i), call. = FALSE)
  }

  NextMethod()
}

#' @export
`print.BlendMode` <- function(x, ...) {
  idx <- x$.ptr + 1L
  label <- c("Clear", "Src", "Dst", "SrcOver", "DstOver", "SrcIn", "DstIn", "SrcOut", "DstOut", "SrcATop", "DstATop", "Xor", "Plus", "Modulate", "Screen", "Overlay", "Darken", "Lighten", "ColorDodge", "ColorBurn", "HardLight", "SoftLight", "Difference", "Exclusion", "Multiply", "Hue", "Saturation", "Color", "Luminosity")[idx]
  if (is.na(label)) {
    stop("Unexpected value for BlendMode", call. = TRUE)
  }
  cat("BlendMode::", label, sep = "")
}


### associated functions for BlendMode



class(`BlendMode`) <- c("BlendMode__bundle", "savvy_skiagd__sealed")

#' @export
`print.BlendMode__bundle` <- function(x, ...) {
  cat('BlendMode')
}

### wrapper functions for Cap


`.savvy_wrap_Cap` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr


  class(e) <- c("Cap", "savvy_skiagd__sealed")
  e
}


#' Cap (0-2)
#'
#' @seealso
#' [Cap in skia_safe::paint - Rust](https://rust-skia.github.io/doc/skia_safe/paint/enum.Cap.html)
#' @export
`Cap` <- new.env(parent = emptyenv())
`Cap`$`Butt` <- .savvy_wrap_Cap(0L)
`Cap`$`Round` <- .savvy_wrap_Cap(1L)
`Cap`$`Square` <- .savvy_wrap_Cap(2L)

#' @export
`$.Cap__bundle` <- function(x, name) {
  if (!name %in% c("Butt", "Round", "Square")) {
    stop(paste0("Unknown variant: ", name), call. = FALSE)
  }

  NextMethod()
}

#' @export
`[[.Cap__bundle` <- function(x, i) {
  if (is.numeric(i)) {
    stop("Cap cannot be subset by index", call. = FALSE)
  }

  if (!i %in% c("Butt", "Round", "Square")) {
    stop(paste0("Unknown variant: ", i), call. = FALSE)
  }

  NextMethod()
}

#' @export
`print.Cap` <- function(x, ...) {
  idx <- x$.ptr + 1L
  label <- c("Butt", "Round", "Square")[idx]
  if (is.na(label)) {
    stop("Unexpected value for Cap", call. = TRUE)
  }
  cat("Cap::", label, sep = "")
}


### associated functions for Cap



class(`Cap`) <- c("Cap__bundle", "savvy_skiagd__sealed")

#' @export
`print.Cap__bundle` <- function(x, ...) {
  cat('Cap')
}

### wrapper functions for Join


`.savvy_wrap_Join` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr


  class(e) <- c("Join", "savvy_skiagd__sealed")
  e
}


#' Join (0-2)
#'
#' @seealso
#' [Join in skia_safe::paint - Rust](https://rust-skia.github.io/doc/skia_safe/paint/enum.Join.html)
#' @export
`Join` <- new.env(parent = emptyenv())
`Join`$`Miter` <- .savvy_wrap_Join(0L)
`Join`$`Round` <- .savvy_wrap_Join(1L)
`Join`$`Bevel` <- .savvy_wrap_Join(2L)

#' @export
`$.Join__bundle` <- function(x, name) {
  if (!name %in% c("Miter", "Round", "Bevel")) {
    stop(paste0("Unknown variant: ", name), call. = FALSE)
  }

  NextMethod()
}

#' @export
`[[.Join__bundle` <- function(x, i) {
  if (is.numeric(i)) {
    stop("Join cannot be subset by index", call. = FALSE)
  }

  if (!i %in% c("Miter", "Round", "Bevel")) {
    stop(paste0("Unknown variant: ", i), call. = FALSE)
  }

  NextMethod()
}

#' @export
`print.Join` <- function(x, ...) {
  idx <- x$.ptr + 1L
  label <- c("Miter", "Round", "Bevel")[idx]
  if (is.na(label)) {
    stop("Unexpected value for Join", call. = TRUE)
  }
  cat("Join::", label, sep = "")
}


### associated functions for Join



class(`Join`) <- c("Join__bundle", "savvy_skiagd__sealed")

#' @export
`print.Join__bundle` <- function(x, ...) {
  cat('Join')
}

### wrapper functions for PaintProps


`.savvy_wrap_PaintProps` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr


  class(e) <- c("PaintProps", "savvy_skiagd__sealed")
  e
}


#' PaintProps
#'
#' Internal impl that wraps `skia_safe::Paint`.
#' Use `PaintProps$set_props()` to create a pointer to PaintProps.
#'
#' @details
#' `PaintProps$set_props()` takes arguments below:
#'
#' * color: RGBA representaion of a color.
#' * style: Style (stroke style).
#' * join: Join (stroke join).
#' * cap: Cap (stroke cap).
#' * lty: Line type. FIXME: Currently not used.
#' * width: Stroke width.
#' * miter: Stroke miter.
#' * blend_mode: BlendMode.
#'
#' @noRd
`PaintProps` <- new.env(parent = emptyenv())

### associated functions for PaintProps

`PaintProps`$`set_props` <- function(`color`, `style`, `join`, `cap`, `lty`, `width`, `miter`, `blend_mode`) {
  `style` <- .savvy_extract_ptr(`style`, "Style")
  `join` <- .savvy_extract_ptr(`join`, "Join")
  `cap` <- .savvy_extract_ptr(`cap`, "Cap")
  `blend_mode` <- .savvy_extract_ptr(`blend_mode`, "BlendMode")
  .savvy_wrap_PaintProps(.Call(savvy_PaintProps_set_props__impl, `color`, `style`, `join`, `cap`, `lty`, `width`, `miter`, `blend_mode`))
}


class(`PaintProps`) <- c("PaintProps__bundle", "savvy_skiagd__sealed")

#' @export
`print.PaintProps__bundle` <- function(x, ...) {
  cat('PaintProps')
}

### wrapper functions for PointMode


`.savvy_wrap_PointMode` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr


  class(e) <- c("PointMode", "savvy_skiagd__sealed")
  e
}


#' PointMode (0-2)
#'
#' This is for [add_point()] only.
#' Not used in other functions.
#'
#' @seealso
#' [PointMode in skia_safe::canvas - Rust](https://rust-skia.github.io/doc/skia_safe/canvas/enum.PointMode.html)
#' @export
`PointMode` <- new.env(parent = emptyenv())
`PointMode`$`Points` <- .savvy_wrap_PointMode(0L)
`PointMode`$`Lines` <- .savvy_wrap_PointMode(1L)
`PointMode`$`Polygon` <- .savvy_wrap_PointMode(2L)

#' @export
`$.PointMode__bundle` <- function(x, name) {
  if (!name %in% c("Points", "Lines", "Polygon")) {
    stop(paste0("Unknown variant: ", name), call. = FALSE)
  }

  NextMethod()
}

#' @export
`[[.PointMode__bundle` <- function(x, i) {
  if (is.numeric(i)) {
    stop("PointMode cannot be subset by index", call. = FALSE)
  }

  if (!i %in% c("Points", "Lines", "Polygon")) {
    stop(paste0("Unknown variant: ", i), call. = FALSE)
  }

  NextMethod()
}

#' @export
`print.PointMode` <- function(x, ...) {
  idx <- x$.ptr + 1L
  label <- c("Points", "Lines", "Polygon")[idx]
  if (is.na(label)) {
    stop("Unexpected value for PointMode", call. = TRUE)
  }
  cat("PointMode::", label, sep = "")
}


### associated functions for PointMode



class(`PointMode`) <- c("PointMode__bundle", "savvy_skiagd__sealed")

#' @export
`print.PointMode__bundle` <- function(x, ...) {
  cat('PointMode')
}

### wrapper functions for Style


`.savvy_wrap_Style` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr


  class(e) <- c("Style", "savvy_skiagd__sealed")
  e
}


#' Style (0-2)
#'
#' @seealso
#' [Style in skia_safe::paint - Rust](https://rust-skia.github.io/doc/skia_safe/paint/enum.Style.html)
#' @export
`Style` <- new.env(parent = emptyenv())
`Style`$`StrokeAndFill` <- .savvy_wrap_Style(0L)
`Style`$`Stroke` <- .savvy_wrap_Style(1L)
`Style`$`Fill` <- .savvy_wrap_Style(2L)

#' @export
`$.Style__bundle` <- function(x, name) {
  if (!name %in% c("StrokeAndFill", "Stroke", "Fill")) {
    stop(paste0("Unknown variant: ", name), call. = FALSE)
  }

  NextMethod()
}

#' @export
`[[.Style__bundle` <- function(x, i) {
  if (is.numeric(i)) {
    stop("Style cannot be subset by index", call. = FALSE)
  }

  if (!i %in% c("StrokeAndFill", "Stroke", "Fill")) {
    stop(paste0("Unknown variant: ", i), call. = FALSE)
  }

  NextMethod()
}

#' @export
`print.Style` <- function(x, ...) {
  idx <- x$.ptr + 1L
  label <- c("StrokeAndFill", "Stroke", "Fill")[idx]
  if (is.na(label)) {
    stop("Unexpected value for Style", call. = TRUE)
  }
  cat("Style::", label, sep = "")
}


### associated functions for Style



class(`Style`) <- c("Style__bundle", "savvy_skiagd__sealed")

#' @export
`print.Style__bundle` <- function(x, ...) {
  cat('Style')
}

