# Generated by cpp11: do not edit by hand

test1 <- function() {
  .Call(`_skiagd_test1`)
}

test2 <- function(fill) {
  .Call(`_skiagd_test2`, fill)
}

sk_save_png <- function(size, curr_bytes, filename) {
  .Call(`_skiagd_sk_save_png`, size, curr_bytes, filename)
}

sk_absolute_fill <- function(size, fill) {
  .Call(`_skiagd_sk_absolute_fill`, size, fill)
}

sk_circle <- function(size, curr_bytes, x, y, r, props) {
  .Call(`_skiagd_sk_circle`, size, curr_bytes, x, y, r, props)
}
