# Generated by cpp11: do not edit by hand

test <- function(props) {
  .Call(`_skiagd_test`, props)
}

sk_save_png <- function(size, curr_bytes, filename) {
  .Call(`_skiagd_sk_save_png`, size, curr_bytes, filename)
}

sk_absolute_fill <- function(size, fill) {
  .Call(`_skiagd_sk_absolute_fill`, size, fill)
}

sk_points <- function(size, curr_bytes, mat_pts, props, mode) {
  .Call(`_skiagd_sk_points`, size, curr_bytes, mat_pts, props, mode)
}

sk_line <- function(size, curr_bytes, mat_from, mat_to, props) {
  .Call(`_skiagd_sk_line`, size, curr_bytes, mat_from, mat_to, props)
}

sk_circle <- function(size, curr_bytes, mat_center, vec_radius, props) {
  .Call(`_skiagd_sk_circle`, size, curr_bytes, mat_center, vec_radius, props)
}

sk_irect <- function(size, curr_bytes, mat_rect, props) {
  .Call(`_skiagd_sk_irect`, size, curr_bytes, mat_rect, props)
}

sk_svg_path <- function(size, curr_bytes, vec_svg, translate, scale, props) {
  .Call(`_skiagd_sk_svg_path`, size, curr_bytes, vec_svg, translate, scale, props)
}
